### ISSUE TITLE
can not setup qm env against c9s due to `set-ffi-env-e2e` failure

### ISSUE THREAD

**Issue by pengshanyu** [containers/qm#662] opened 2024-11-15 03:55 UTC
Provision a VM locally with c9s image, then run the ffi tests `tmt -c scenario=ffi -c run=manual -c distro=centos-stream-9 run -e PACKIT_COPR_PROJECT="packit/containers-qm-613" -a -vvv discover execute  provision   --how connect  -u root -p 123 -g localhost -P 2222   plan -n /plans/e2e/ffi test -n /tests/ffi/agent-flood`, then met the issue below:

```
err: + [[ packit/containers-qm-613 != \r\e\l\e\a\s\e ]]
            err: ++ arch
            err: + dnf copr enable -y @centos-automotive-sig/bluechi-snapshot --x86_64
            err: usage: dnf copr [-c [config file]] [-q] [-v] [--version]
            err:                 [--installroot [path]] [--nodocs] [--noplugins]
            err:                 [--enableplugin [plugin]] [--disableplugin [plugin]]
            ......
            err:                 [--hub HUB]
            err:                 {help,enable,disable,remove,list,search} [arg ...]
            err: dnf copr: error: unrecognized arguments: --x86_64
            err: ++ arch
            err: + dnf copr enable -y packit/containers-qm-613 --x86_64
            err: usage: dnf copr [-c [config file]] [-q] [-v] [--version]
            err:                 [--installroot [path]] [--nodocs] [--noplugins]
            err:                 [--enableplugin [plugin]] [--disableplugin [plugin]]
           ......
            err:                 [--hub HUB]
            err:                 {help,enable,disable,remove,list,search} [arg ...]
            err: dnf copr: error: unrecognized arguments: --x86_64

```

**Comment by pengshanyu** [comment] 2024-11-15 08:23
I saw the changes and README from https://github.com/containers/qm/pull/652

**Comment by Yarboa** [comment] 2024-11-17 08:54
The problem is the content of /etc/os-release
I will add a '"' removel of values in the file

**Comment by Yarboa** [comment] 2024-11-17 10:41
Please refer this fix 
https://github.com/containers/qm/pull/657/files#diff-ed4cd590d534395a418d961acd614ebff97ed5889b9ca785094dd0a10d27863dR160

**Comment by dougsland** [comment] 2024-11-18 12:45
The error is clear:
`        err: dnf copr: error: unrecognized arguments: --x86_64`

Where this --x86_64 I am not sure @Yarboa 

Maybe, just maybe:

- If the ID line in /etc/os-release has additional spaces, special characters, or formatting differences, it could lead to unintended values being assigned to release_id.
- If release_id is used to construct another command or as a flag, unexpected behavior (like --x86_64 being appended) could occur due to improper parsing.

How about 
```
release_id=$(grep -oP '(?<=^ID=)\w+' <<< "$(tr -d '"' < /etc/os-release)")
if [[ -z "$release_id" ]]; then
    echo "Error: Unable to extract a valid release_id."
    exit 1
fi
```

@pengshanyu you want to try to solve this one ?

**Comment by Yarboa** [comment] 2024-11-18 15:51
@pengshanyu can you give it a try ?
in case it is working, please close this ticket

**Comment by pengshanyu** [comment] 2024-11-19 03:00
@Yarboa Thank you so much for the fix.
I checked when `PACKIT_COPR_PROJECT="packit/containers-qm-658" ` it works, but when `PACKIT_COPR_PROJECT=release` it fails with the following error:

```
 err: + local release_id
            err: ++ grep -oP '(?<=^ID=)\w+'
            err: +++ tr -d '"'
            err: + release_id=centos
            err: + local version_id
            err: ++ grep -oP '(?<=^VERSION_ID=)\w+'
            err: +++ tr -d '"'
            err: + version_id=9
            err: + [[ centos == \c\e\n\t\o\s ]]
            err: + release_id=epel
            err: + [[ -n release ]]
            err: + [[ release != \r\e\l\e\a\s\e ]]
            err: + [[ release == \r\e\l\e\a\s\e ]]
            err: + [[ epel =~ (centos|fedora) ]]
            err: + dnf install -y bluechi-ctl bluechi-agent bluechi-controller qm hostname
            out: CentOS Stream 9 - BaseOS                        9.0 kB/s | 7.5 kB     00:00    
            out: CentOS Stream 9 - AppStream                     9.9 kB/s | 7.7 kB     00:00    
            out: CentOS Stream 9 - CRB                           2.3 MB/s | 6.7 MB     00:02    
            out: No match for argument: bluechi-ctl
            out: No match for argument: bluechi-agent
            out: No match for argument: bluechi-controller
            out: No match for argument: qm
            out: Package hostname-3.23-6.el9.x86_64 is already installed.
            err: Error: Unable to find a match: bluechi-ctl bluechi-agent bluechi-controller qm
```
It seems that the problem is caused by L164 and L171 of `set-ffi-env-e2e`

**Comment by Yarboa** [comment] 2024-11-27 12:56
Hi @pengshanyu it is not the correct way to work with release
Please see this 
https://github.com/containers/qm/blob/main/tests/e2e/set-ffi-env-e2e#L57C1-L57C30

Ahh but yes, we need to fix that, thanks

**Comment by Yarboa** [comment] 2024-12-03 09:53
@pengshanyu 
Tested this with the following tmt commands 
```
tmt -c distro=fedroa-41 -c run=manual  run  -e PACKIT_COPR_PROJECT=release  prepare -vvv -d  provision --how connect -u root  -g 10.0.57.131 plans -n /plans/e2e/tier-0 exec -d -vvv report --how junit
```

Currently it is failing on release containers.conf
once new release exist, whole prepare will finish correct.

**Closed** 2024-12-03 09:54 UTC
Labels: bug, jira, Priority: high

**Comment by pengshanyu** [comment] 2024-12-04 08:56
Hi @Yarboa ,
Yes, I tried to run ffi test against c9s image as follows:
`tmt -c scenario=ffi -c distro=centos-stream-9 -c run=manual run -e PACKIT_COPR_PROJECT=release -a -vvv discover execute  provision   --how connect  -u root -g localhost -P 2222 plan -n /plans/e2e/ffi test -n /tests/ffi`

and it fails in containers.conf
```
+ if_error_exit 'Error: Command grep -o '\''\(nproc.*",\|nofile.*"\)'\'' /etc/qm/containers/containers.conf | tr -d '\''",'\''  failed'
        + local exit_code=1
        + '[' 1 '!=' 0 ']'
        + RED='\033[91m'
        + ENDCOLOR='\033[0m'
        + echo -e '[ \033[91mFAILED\033[0m ] Error: Command grep -o '\''\(nproc.*",\|nofile.*"\)'\'' /etc/qm/containers/containers.conf | tr -d '\''",'\''  failed with exit code: 1'
        + kill 3776
        Terminated
```
"once new release exist, whole prepare will finish correct."
What exactly do you mean by "new release "?
